14_deadlock_01: 14_deadlock_01.cpp
	g++ -o 14_deadlock_01 14_deadlock_01.cpp -pthread

15_deadlock_02: 15_deadlock_02.cpp
	g++ -o 15_deadlock_02 15_deadlock_02.cpp -pthread

16_deadlock_03: 16_deadlock_03.cpp
	g++ -o 16_deadlock_03 16_deadlock_03.cpp -pthread

17_deadlock_04: 17_deadlock_04.cpp
	g++ -o 17_deadlock_04 17_deadlock_04.cpp -pthread

18_deadlock_05: 18_deadlock_05.cpp
	g++ -o 18_deadlock_05 18_deadlock_05.cpp -pthread

19_deadlock_06: 19_deadlock_06.cpp
	g++ -o 19_deadlock_06 19_deadlock_06.cpp -pthread

clean:
	rm -f 14_deadlock_01 15_deadlock_02 16_deadlock_03 17_deadlock_04 18_deadlock_05 19_deadlock_06