10_deadlock_01: 10_deadlock_01.cpp
	g++ -o 10_deadlock_01 10_deadlock_01.cpp -pthread

11_deadlock_02: 11_deadlock_02.cpp
	g++ -o 11_deadlock_02 11_deadlock_02.cpp -pthread

12_deadlock_03: 12_deadlock_03.cpp
	g++ -o 12_deadlock_03 12_deadlock_03.cpp -pthread

13_deadlock_04: 13_deadlock_04.cpp
	g++ -o 13_deadlock_04 13_deadlock_04.cpp -pthread

14_deadlock_05: 14_deadlock_05.cpp
	g++ -o 14_deadlock_05 14_deadlock_05.cpp -pthread

15_deadlock_06: 15_deadlock_06.cpp
	g++ -o 15_deadlock_06 15_deadlock_06.cpp -pthread

clean:
	rm -f 10_deadlock_01 11_deadlock_02 12_deadlock_03 13_deadlock_04 14_deadlock_05 15_deadlock_06