12_readers_writers_01: 12_readers_writers_01.cpp
	g++ -o 12_readers_writers_01 12_readers_writers_01.cpp -pthread

13_readers_writers_02: 13_readers_writers_02.cpp
	g++ -o 13_readers_writers_02 13_readers_writers_02.cpp -pthread

clean:
	rm -f 