16_producer_consumer_01: 16_producer_consumer_01.cpp
	g++ -o 16_producer_consumer_01 16_producer_consumer_01.cpp -pthread

17_producer_consumer_02: 17_producer_consumer_02.cpp
	g++ -o 17_producer_consumer_02 17_producer_consumer_02.cpp -pthread

clean:
	rm -f 16_producer_consumer_01 17_producer_consumer_02