10_producer_consumer_01: 10_producer_consumer_01.cpp
	g++ -o 10_producer_consumer_01 10_producer_consumer_01.cpp -pthread

11_producer_consumer_02: 11_producer_consumer_02.cpp
	g++ -o 11_producer_consumer_02 11_producer_consumer_02.cpp -pthread

clean:
	rm -f 10_producer_consumer_01 11_producer_consumer_02