6_raceCondition_01: 6_raceCondition_01.cpp
	g++ -o 6_raceCondition_01 6_raceCondition_01.cpp

7_raceCondition_02: 7_raceCondition_02.cpp
	g++ -o 7_raceCondition_02 7_raceCondition_02.cpp -pthread

8_raceCondition_03: 8_raceCondition_03.cpp
	g++ -o 8_raceCondition_03 8_raceCondition_03.cpp -pthread

9_conditionVariable: 9_conditionVariable.cpp
	g++ -o 9_conditionVariable 9_conditionVariable.cpp -pthread

clean:
	rm -f 6_raceCondition_01 7_raceCondition_02 8_raceCondition_03 9_conditionVariable