18_readers_writers_01: 18_readers_writers_01.cpp
	g++ -o 18_readers_writers_01 18_readers_writers_01.cpp -pthread

19_readers_writers_02: 19_readers_writers_02.cpp
	g++ -o 19_readers_writers_02 19_readers_writers_02.cpp -pthread

clean:
	rm -f 18_readers_writers_01 19_readers_writers_02